### ISSUE TITLE
Kafka ChannelTemplate Spec (numPartitions, replicationFactor) not working for Sequence Flows

### ISSUE THREAD

**Issue by holoed** [knative-sandbox/eventing-kafka#1014]
**Describe the bug**
The following fails to create the sequence flow:

```yaml
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence-example
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    spec:
        numPartitions: 10
        replicationFactor: 1
  steps:
  ....
```
 **Expected behavior**
I expect it to behave like the Parallel flows that correctly generates the subscriptions and the appropriately configured channels.

This works fine:
```yaml
apiVersion: flows.knative.dev/v1
kind: Parallel
metadata:
  name: parallel-example
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    spec:
        numPartitions: 10
        replicationFactor: 1
  steps:
 ....
```
 **To Reproduce**
Steps to reproduce the behavior.
- Install Kafka
- Install Knative Serving and Eventing
- Install Channel yaml files (I tried with both channel-consolidated and channel-distributed, same behaviour)
- Create a bunch of Knative services and wired them together with a Parallel and Sequence flows
- In my configuration I have a parallel flow folllowed by a sequence flow connected with the reply tag.

 **Knative release version**
Tried on Latest Nightly Build and v0.26.6

 **Additional context**
I need this to be working for Knative to be considered ready for my company projects.
