### ISSUE TITLE
status.DeadLetterSinkURI cannot be set on KafkaChannel

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#1056]
**Describe the bug**
`status.DeadLetterSinkURI` cannot be set on KafkaChannel because the CRD doesn't have that field. When the code sets it, Kube API server will ignore that field.

Why is that relevant? Without setting the value on the field, Subscription controller complains, when the DLS information is not set on the subscription and it should fallback to the DLS information on the channel.

Releavant code:
* Subscription controller complaining: https://github.com/knative/eventing/blob/820db20be4b2219e12ad6757ca5de1252bebd0b6/pkg/reconciler/subscription/subscription.go#L292
* IMC CRD: https://github.com/knative/eventing/blob/c7e9acb806cafdf0ddd77ea3a5ee545d0d4d267d/config/channels/in-memory-channel/resources/in-memory-channel.yaml#L193-L195

 **Expected behavior**
`status.DeadLetterSinkURI` should be set properly.

 **To Reproduce**

Create event-display service:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: event-display
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: event-display
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: event-display
  name: event-display
spec:
  containers:
  - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
    name: event-display
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

```

Create KafkaChannel with DLS defined:
```
apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: kafka-channel
spec:
  delivery:
    deadLetterSink:
      ref:
        apiVersion: v1
        kind: Service
        name: event-display
```

Create Subscription for the 2 things above, but w/o DLS:
```
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: subscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: kafka-channel
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: failing-sink
```

Create `failing-sink` as well, though things don't get thru that much and you get this output:

* KafkaChannel doesn't have a `status.DeadLetterSinkURI`
* Subscription:

```
status:
  72   │     conditions:
  73   │     - lastTransitionTime: "2022-01-13T11:31:52Z"
  74   │       status: "True"
  75   │       type: AddedToChannel
  76   │     - lastTransitionTime: "2022-01-13T11:31:53Z"
  77   │       status: "True"
  78   │       type: ChannelReady
  79   │     - lastTransitionTime: "2022-01-13T11:44:21Z"
  80   │       message: channel kafka-channel didn't set status.deadLetterSinkURI
  81   │       reason: DeadLetterSinkResolveFailed
  82   │       status: "False"
  83   │       type: Ready
  84   │     - lastTransitionTime: "2022-01-13T11:44:21Z"
  85   │       message: channel kafka-channel didn't set status.deadLetterSinkURI
  86   │       reason: DeadLetterSinkResolveFailed
```

Here's the `failing-sink` if you like:

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: failing-sink
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: failing-sink
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: failing-sink
  name: failing-sink
spec:
  containers:
  - image: docker.io/aliok/failing-sink
    name: failing-sink
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

```

 **Knative release version**
1.0.1

 **Additional context**
Add any other context about the problem here such as proposed priority
