### ISSUE TITLE
Resetoffset: no matches for kind "ResetOffset" in version "kafka.eventing.knative.dev/v1alpha1"

### ISSUE THREAD

**Issue by zhaojinxin409** [knative-sandbox/eventing-kafka#1091]
**Describe the bug**

When i create the `ResetOffset` using `kubectl create -f reset.yaml` and it reports error: `error: unable to recognize "reset.yaml": no matches for kind "ResetOffset" in version "kafka.eventing.knative.dev/v1alpha1"`

I don't know whether this is a bug or is there something missing.

reset.yaml:
```
apiVersion: kafka.eventing.knative.dev/v1alpha1
kind: ResetOffset
metadata:
  name: test
  namespace: camel
spec:
  offset:
    time: 2021-02-15T02:33:00Z
  ref:
    apiVersion: messaging.knative.dev/v1
    kind: Subscription
    namespace: camel
    name: eb0208-camel-testzjx0208-0-1aa52add-ccf5-446a-ae7d-c3ef3e75b7a5
```

And i have add the `RESETOFFSET_SUPPORT` env to `true`, this is webhook's pod:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kafka-webhook
    pod-template-hash: 76d879ff6f
    role: kafka-webhook
  name: kafka-webhook-76d879ff6f-qjs8c
  namespace: knative-eventing
spec:
  containers:
  - env:
    - name: SYSTEM_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: CONFIG_LOGGING_NAME
      value: config-logging
    - name: METRICS_DOMAIN
      value: knative.dev/eventing
    - name: WEBHOOK_NAME
      value: kafka-webhook
    - name: WEBHOOK_PORT
      value: "8443"
    - name: RESETOFFSET_SUPPORT
      value: "true"
    image: xxx.net/release/knative-eventing-kafka-ch-webhook:v1.1.2
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        httpHeaders:
        - name: k-kubelet-probe
          value: webhook
        path: /
        port: 8443
        scheme: HTTPS
      initialDelaySeconds: 20
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    name: kafka-webhook
```

 **Knative release version**
  
v1.1.2

 **Additional context**

all pod are running:
```
NAME                                        READY   STATUS    RESTARTS   AGE
eventing-controller-69bb5945d9-ftgzl        1/1     Running   1          6d1h
eventing-webhook-56749cb74d-c5dtz           1/1     Running   1          6d1h
imc-controller-67c455df67-zjhzs             1/1     Running   2          6d1h
imc-dispatcher-546dc89d6f-rzp2t             1/1     Running   1          6d1h
kafka-ch-controller-c5548ccfd-s4wdr         1/1     Running   1          6d
kafka-ch-dispatcher-8588d7d4f6-b4kwh        1/1     Running   5          6d
kafka-controller-manager-7fb7d4bdf7-2skzd   1/1     Running   5          21d
kafka-webhook-76d879ff6f-qjs8c              1/1     Running   0          158m
mt-broker-controller-7d97585d8d-t7fjf       1/1     Running   1          6d1h
mt-broker-filter-8684bb48b5-m2qkr           1/1     Running   1          6d1h
mt-broker-ingress-5dd79fdb9-qz8qw           1/1     Running   2          6d1h
sugar-controller-cbd766595-wgd6g            1/1     Running   1          6d1h
```
