### ISSUE TITLE
ConsumerGroup is not cleaned up after KafkaSource deletion

### ISSUE THREAD

**Issue by a7i** [knative-sandbox/eventing-kafka#1238]
**Describe the bug**
Deletion of `KafkaSource` does not clean up the `ConsumerGroup`. Even t hough `KafkaSource` is the ownerRef for `ConsumerGroup`

i.e. 
```
apiVersion: internal.kafka.eventing.knative.dev/v1alpha1
kind: ConsumerGroup
metadata:
  ownerReferences:
  - apiVersion: sources.knative.dev/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: KafkaSource
    name: ....
    uid: ...
```
This is because the `ConsumerGroup` finalizer is blocking it.

 **Expected behavior**
If a `KafkaSource` is deleted, then the `ConsumerGroup` also needs to be deleted.

 **To Reproduce**
1. Create a `KafkaSource`
2. Observe that a `ConsumerGroup` is created
3. Delete the `KafkaSource`
4. Observe that the `ConsumerGroup` is not deleted
    1. Also `kubectl delete consumergroup ...` does not work and requires removing the finalizers

 **Knative release version**
`v1.6.0`

 **Additional context**
Add any other context about the problem here such as proposed priority
