### ISSUE TITLE
Consumers created by KafkaSource don't forward requests concurrently

### ISSUE THREAD

**Issue by ashrafguitoni** [knative-sandbox/eventing-kafka#1245]
## Expected Behavior

When using a `KafkaSource` to expose a simple web application via a Kafka topic, the service (which is deployed with `containerConcurrency` > 1) receives multiple requests (from Kafka topic messages) and handles them concurrently.

## Actual Behavior

The service only receives one request at a time from the Kafka consumers (even if `consumers` > 1 in `KafkaSource` and the topic has a number of partitions > 1). This means that even if my service is configured to handle many concurrent requests, they end up waiting for each other.

## Steps to Reproduce the Problem

1. Deploy Kafka and create a topic with partitions > 1:
    ```bash
    helm upgrade --install minio minio --repo https://charts.bitnami.com/bitnami -f values.yaml
    ```
    with `values.yaml` containing the following:
    ```yaml
    provisioning:
      enabled: true
      topics:
      - name: concurrency-test-requests
        partitions: 2
        replicationFactor: 2
    ```
2. Deploy a Knative `service` and a `KafkaSource`:
    ```yaml
    apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      name: concurrency-test
    spec:
      template:
        metadata:
          annotations:
            autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
            autoscaling.knative.dev/metric: "concurrency"
            autoscaling.knative.dev/target: "5"
        spec:
          containerConcurrency: 5
          containers:
            - name: app
              image: dev.local/concurrency-test:latest
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8877
    ---
    apiVersion: sources.knative.dev/v1beta1
    kind: KafkaSource
    metadata:
      name: concurrency-test
    spec:
      consumerGroup: concurrency-test-group
      bootstrapServers:
      - kafka.default.svc.cluster.local:9092
      topics:
      - concurrency-test-requests
      sink:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: concurrency-test
    ```
    
    with `dev.local/concurrency-test:latest` built from this Dockerfile:
    ```dockerfile
    FROM python:3.9-slim
    RUN pip install fastapi uvicorn kafka-python
    ADD main.py .
    ENTRYPOINT uvicorn --host 0.0.0.0 --port 8877 main:app
    ```
  
    and `main.py` containing:
    ```python
    import asyncio
    from fastapi import FastAPI
    from pydantic import BaseModel
    import logging

    logging.basicConfig(format="%(asctime)s %(levelname)-8s %(message)s", level=logging.DEBUG, datefmt="%Y-%m-%d %H:%M:%S")

    app = FastAPI()

    class Item(BaseModel):
        id: str

    @app.post("/")
    async def root(item: Item):
        logging.debug(f"Request received with ID: {item.id}")
        await asyncio.sleep(5)
        logging.debug(f"Request complete for ID: {item.id}")
        return {"message": "Hello World"}
    ```
    
3. Exec into the service pod (because `kafka-python` is installed on it for convenience) then run the following in the python console:
    ```python
    import kafka
    import json
    serializer = lambda m: json.dumps(m).encode("utf-8")
    producer = kafka.KafkaProducer(bootstrap_servers=["kafka.default.svc.cluster.local:9092"], value_serializer=serializer)
    producer.send("concurrency-test-requests", {"id": "111"})
    producer.send("concurrency-test-requests", {"id": "222"})
    ```

    The output of these messages is something like:
    ```bash
    2022-09-12 02:14:55 DEBUG    Request received with ID: 111
    2022-09-12 02:15:00 DEBUG    Request complete for ID: 111
    INFO:     10.42.0.7:0 - "POST / HTTP/1.1" 200 OK
    2022-09-12 02:15:00 DEBUG    Request received with ID: 222
    2022-09-12 02:15:05 DEBUG    Request complete for ID: 222
    INFO:     10.42.0.7:0 - "POST / HTTP/1.1" 200 OK
    ```
    which clearly shows that the Kafka consumers (create by the `KnativeService`) are waiting on each other, in some sense.

## Additional Info:

When sending multiple requests to the service with HTTP to the public service endpoint (I'm using Kourier), the server receives the requests and handles them concurrently, producing logs like the following:
```bash
2022-09-12 02:14:36 DEBUG    Request received with ID: abc
2022-09-12 02:14:37 DEBUG    Request received with ID: def
2022-09-12 02:14:41 DEBUG    Request complete for ID: abc
INFO:     10.42.0.7:0 - "POST / HTTP/1.1" 200 OK
2022-09-12 02:14:42 DEBUG    Request complete for ID: def
INFO:     10.42.0.7:0 - "POST / HTTP/1.1" 200 OK
```
The curl command I'm using to send the HTTP requests is:
```bash
curl http://concurrency-test.default.127.0.0.1.nip.io -H 'Content-Type: application/json' --data-raw '{"id": "abc"}' &
curl http://concurrency-test.default.127.0.0.1.nip.io -H 'Content-Type: application/json' --data-raw '{"id": "def"}'
```

The setup only uses a KafkaSource which points to my KNative Service, and is using a Kafka instance deployed using the bitnami/kafka helm chart.

The version I'm using is v1.7.1 for KNative serving and eventing, and v1.7.0 for the Kafka eventing integration (from knative-sandbox/eventing-kafka).
