### ISSUE TITLE
Installing ob k8s 1.25.1 fails because PodDisruptionBudget does not exist in API version policy/v1beta1

### ISSUE THREAD

**Issue by lenalebt** [knative-sandbox/eventing-kafka#1267]
**Describe the bug**
This file: https://github.com/knative-sandbox/eventing-kafka/releases/download/knative-v1.8.1/channel-consolidated.yaml
contains the following definition:

```
---
# Webhook PDB.
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-webhook
  namespace: knative-eventing
  labels:
    kafka.eventing.knative.dev/release: "v1.8.1"
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: kafka-webhook

---
```
I tried installing this in k8s 1.25.1 on GKE, and it failed, because `PodDisruptionBudget` does not seem to be available in this API version. See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125 for more details, but: It's not available anymore.

Using `apiVersion: policy/v1` worked, though - I patched the file and installed from there. It is available since k8s 1.21 (according to https://stackrox.github.io/k8s-i-use/policy-v1-poddisruptionbudget), and since knative-eventing wants 1.24+, I think it should be safe to upgrade.

 **Expected behavior**
Installs on k8s 1.25+ without issues.

 **To Reproduce**
Try to install on k8s 1.25+.

 **Knative release version**
1.8

 **Additional context**
I was able to work around by downloading the file, patching it locally, and installing from there.
