### ISSUE TITLE
make istio annotation optional

### ISSUE THREAD

**Issue by itsmurugappan** [knative-sandbox/eventing-kafka#294]
**Problem**

The kafka receiver adapter always has the istio proxy side car, currently the annotation `"sidecar.istio.io/inject"` is always set to true. This feature would make it opt in by using the annotation mentioned in the kafkasource

Example
```
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  name: kafka-source-test
spec:
  bootstrapServers:
  - someserver
  consumerGroup: testgrp
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: testsvc
  topics:
  - test
```
