### ISSUE TITLE
Kafka event source does not work with namespace scoped in memory channel

### ISSUE THREAD

**Issue by yuzisun** [knative-sandbox/eventing-kafka#313]
**Describe the bug**
We use kafka event source along with the in memory channel in a multi tenant environment, kafka source -> in memory channel -> subscribers. In order to avoid sharing the same imc dispatcher among tenants we are trying to create namespace scoped imc channels, however this does not work as intended and we get HTTP 404 error after switching to namespace scoped imc channel.

```
{"level":"error","ts":"2021-01-15T07:26:27.848Z","logger":"kafkasource","caller":"adapter/adapter.go:153","msg":"An error has occurred while consuming messages occurred: ","error":"error sending cloudevent: 404 Not Found","stacktrace":"knative.dev/eventing-contrib/kafka/source/pkg/adapter.(*Adapter).Start.func3\n\tknative.dev/eventing-contrib/kafka/source/pkg/adapter/adapter.go:153"}
{"level":"debug","ts":"2021-01-15T07:26:27.855Z","logger":"kafkasource","caller":"adapter/adapter.go:204","msg":"Error while sending the message","error":"error sending cloudevent: 404 Not Found"}
{"level":"info","ts":"2021-01-15T07:26:27.855Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:82","msg":"Failure while handling a message","topic":"readtest","partition":0,"offset":447,"error":"error sending cloudevent: 404 Not Found"}
```

 **Expected behavior**
kafka event source should be able to deliver to namespace scoped imc channel.

 **To Reproduce**
 1. Create imc channel
 ```
apiVersion: messaging.knative.dev/v1
kind: InMemoryChannel
metadata:
  annotations:
    eventing.knative.dev/scope: namespace
  name: readtest-input
  namespace: devtest
spec:
  subscribers:
  - delivery:
      deadLetterSink: {}
    subscriberUri: http://testsvc.devtest
```    

```
kubectl get inmemorychannels 
NAME                        READY   REASON   URL                                                                       AGE
readtest-input   True             http://readtest-input-kn-channel.devtest.svc.cluster.local   6d14h
```

2. Create kafka event source 
```
kind: KafkaSource
metadata:
  name: readtest-4q4gt
  namespace: devtest
spec:
  bootstrapServers: my-kafka-cp-kafka.knative-pubsub:9092
  consumerGroup: readtest-4q4gt
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: InMemoryChannel
      name: readtest-input
      namespace: devtest
  topics: readtest
```  

3. imc-dispatcher is created in the devtest namespace instead of knative-eventing and service is pointing to the ` imc-dispatcher` in devtest namespace correctly
```
kubectl get svc readtest-input-kn-channel 
NAME                                   TYPE           CLUSTER-IP   EXTERNAL-IP                                  PORT(S)   AGE
readtest-input-kn-channel   ExternalName   <none>       imc-dispatcher.devtest.svc.cluster.local   <none>    6d14h
```

4. When you produce an event to the `readtest` kafka topic, you get 404 error in the kafka event source pod log, this works if you remove the namespace scope annotation from the imc channel.
```
{"level":"error","ts":"2021-01-15T07:26:27.855Z","logger":"kafkasource","caller":"adapter/adapter.go:153","msg":"An error has occurred while consuming messages occurred: ","error":"error sending cloudevent: 404 Not Found","stacktrace":"knative.dev/eventing-contrib/kafka/source/pkg/adapter.(*Adapter).Start.func3\n\tknative.dev/eventing-contrib/kafka/source/pkg/adapter/adapter.go:153"}
{"level":"debug","ts":"2021-01-15T07:26:27.861Z","logger":"kafkasource","caller":"adapter/adapter.go:204","msg":"Error while sending the message","error":"error sending cloudevent: 404 Not Found"}
{"level":"info","ts":"2021-01-15T07:26:27.861Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:82","msg":"Failure while handling a message","topic":"readtest","partition":0,"offset":448,"error":"error sending cloudevent: 404 Not Found"}
{"level":"error","ts":"2021-01-15T07:26:27.861Z","logger":"kafkasource","caller":"adapter/adapter.go:153","msg":"An error has occurred while consuming messages occurred: ","error":"error sending cloudevent: 404 Not Found","stacktrace":"knative.dev/eventing-contrib/kafka/source/pkg/adapter.(*Adapter).Start.func3\n\tknative.dev/eventing-contrib/kafka/source/pkg/adapter/adapter.go:153"}
```
 **Knative release version**
0.17.0
 **Additional context**
Add any other context about the problem here such as proposed priority
