### ISSUE TITLE
Leverage eventing-kafka field of config-kafka in consolidated channel and in source

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-kafka#405]
**Problem**
There's an `eventing-kafka` [field](https://github.com/knative-sandbox/eventing-kafka/blob/master/config/channel/distributed/300-eventing-kafka-configmap.yaml#L39) in `config-kafka` of the distributed channel:

```yaml
eventing-kafka: |
    receiver:
      cpuRequest: 100m
      memoryRequest: 50Mi
      replicas: 1
    dispatcher:
      cpuRequest: 100m
      memoryRequest: 50Mi
      replicas: 1
    kafka:
      brokers: REPLACE_WITH_CLUSTER_URL
      enableSaramaLogging: false
      topic:
        defaultNumPartitions: 4
        defaultReplicationFactor: 1 # Cannot exceed the number of Kafka Brokers!
        defaultRetentionMillis: 604800000  # 1 week
      adminType: kafka # One of "kafka", "azure", "custom"
```

To be consistent (see the umbrella ticket, https://github.com/knative-sandbox/eventing-kafka/issues/404), we can also leverage these settings in consolidated channel and also in Kafka source.

To talk about fields specifically:
- `receiver`: could only be used in distributed channel
- `dispatcher`: could be used in distributed and consolidated channel
- `kafka.brokers`: Consolidated channel has a separete field in `config-kafka` called `bootstrapServers`. We should leverage that in distributed channel too. `eventing-kafka.kafka.brokers` then would be used as a default OR if possible, we can get rid of that.
- `kafka.enableSaramaLogging`: could be used in all 3 components (2 channels and the source)
- `kafka.topic`: could be also used in consolidated channel
- `kafka.adminType`: could be also used in consolidated channel

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by aliok** [comment]
@travis-minke-sap @eric-sap

May I ask you to review the suggestions in the PR?

How flexible are you in terms of changing the structure of `eventing-kafka`?

Maybe something like this would be better?

```
channel:
  receiver:
    cpuRequest: 100m
    memoryRequest: 50Mi
    replicas: 1
    enableSaramaLogging: false
  dispatcher:
    cpuRequest: 100m
    memoryRequest: 50Mi
    replicas: 1
    enableSaramaLogging: false
  topic:
    defaultNumPartitions: 4
    defaultReplicationFactor: 1 # Cannot exceed the number of Kafka Brokers!
    defaultRetentionMillis: 604800000  # 1 week
  kafka:
    adminType: kafka # One of "kafka", "azure", "custom" 
source:
  foo: bar
```

**Comment by travis-minke-sap** [comment]
Hi Ali - Thanks for continuing the effort to align the two implementations - it would be great to share this config!  I'll ask that @eric-sap also review as he's been implementing a lot of this configuration on the distributed kafkachannel.

Responding to your proposal...
- Seems fine to change the top level organization from `eventing-kafka` to `channel`
- In general I am ok with making the `enableSaramaLogging` more granular (receiver/dispatcher) BUT... I think your proposal doesn't include the "controller" which is a separate Deployment/Pod for the distributed kakfachannel.
- Keep in mind (just stating the obvious so it's clear) that the values in `topic.XYZ` are **defaults** which are used **only** in the case when the KafkaChannel CRD doesn't specify them (for NumPartitions & ReplicationFactor).   On that note... It would be good for us to add Retention to the KafkaChannel CRD at some point (we had it in our version of the CRD before we converted over).
- The `kafka.brokers` can be moved/renamed as you suggested - whichever language is more "standard" in the kafka world (I've seen both).  I agree that we wouldn't want to have two though - just move and rename to match, etc.  Also, fwiw... Eric just moved that from our Secret to the ConfigMap yesterday in order to better align with consolidated!
- The `adminType` field would be great for the consolidated implementation to support, and that was my goal with #297 but I ran into a blocker making the adminClient interface usable by the consolidated channel.  This is because in order to support azure/custom/etc. I've wrapped the sarama admin client with a slimmed down interface which just creates/deletes topics.  This is all the distributed version needs, but.. the consolidated versions is/was using the adminclient to get a list of consumergroups in order to manage status of the kafkachannel.   Soooo... we'll have to find a solution to that before the `adminType` field can be supported by the consolidated channel.  Totally do-able I'm sure just need to sort it out ; )


* As part of all this work we have a simple wrapper function in pkg/channel/distributed/common/kafka/sarama called EnableSaramaLogging() that should probably be moved to pkg/common.

**Comment by eric-sap** [comment]
Adjusting the format of that configmap shouldn't be a big issue, though it would need to be a few bits of changes in various places as the main EventingKafkaConfig struct in pkg/channel/distributed/common/config/configwatcher.go would need to be adjusted to match (which would trigger the need for some one-line-type modifications in the places that use that struct).
As for the particular new format, I have no attachment or druthers for anything existing.

**Comment by aliok** [comment]
> Seems fine to change the top level organization from eventing-kafka to channel

Actually, that wasn't my intention. I just wanted a `channel` field as a child of `eventing-kafka` field, so that we can have a `source` field as well.

It can be like:
```
kind: Configmap
data:
  eventing-kafka: |
    channel: ...
    source: ...
```

> In general I am ok with making the enableSaramaLogging more granular (receiver/dispatcher) BUT... I think your proposal doesn't include the "controller" which is a separate Deployment/Pod for the distributed kakfachannel.

Ok, let's not do this.

> I agree that we wouldn't want to have two though - just move and rename to match, etc

Yes. Apart from naming, I think we should change this to a top level field in `config-kafka` as it is like that in consolidated. OR, have it in `eventing-kafka` like distributed channel. 
When I think about it, having it under a `channel` field sounds better now since it is irrelevant for sources (sources define the Kafka servers in their CRDs). See below.

Another go at the `config-kafka`(with less disruption after I've read the reasons why you organized `eventing-kafka` field like that):

```
data:
  bootstrapServers: REPLACE_WITH_CLUSTER_URL         # ------> this will be deprecated (consolidated uses this)
  authSecretName: name-of-your-secret-for-kafka-auth 
  authSecretNamespace: namespace-of-your-secret-for-kafka-auth                    # -------> needs discussion
  sarama: |
    Version: 2.0.0 # Kafka Version Compatibility From Sarama's Supported List (Major.Minor.Patch)
    ...
  eventing-kafka: |
    channel:
      receiver:             # -----------> only to be used in distributed ch's dispatcher
        cpuRequest: 100m
        memoryRequest: 50Mi
        replicas: 1
      dispatcher:           # -----------> to be used in both ch's dispatchers
        cpuRequest: 100m
        memoryRequest: 50Mi
        replicas: 1
      kafka:
        brokers: REPLACE_WITH_CLUSTER_URL      # ------------> consolidated will also start using this field
        topic:                # -----------> to be used in both channel impls
          defaultNumPartitions: 4
          defaultReplicationFactor: 1 # Cannot exceed the number of Kafka Brokers!
          defaultRetentionMillis: 604800000  # 1 week
        enableSaramaLogging: false
        adminType: kafka # One of "kafka", "azure", "custom"
    source:                 # reserved for future use, not going to be read right now
      foo: bar

```

Top level `authSecretName` and `authSecretNamespace` are used by consolidated channel for auth with Kafka.
Any suggestions to unify the auth?

**Comment by travis-minke-sap** [comment]
👍  On the hierarchy of `channel` and `source` under `eventing-kafka`

👍  On the `authSecretName` and `authSecretNamespace` ... This is something that we want to switch over to once we have the time.  Currently we have a separate Controller which watches the secrets (based on a label).  This was done in the past to support dynamically adding Azure EventHub Namespace secrets (which have a limited number of Topics).  I've since removed that capability, and we no longer need/want to watch the secrets and instead want to align with the consolidated implementation by using a specified namespace/name in the configmap as you suggest.  I think you can proceed with adding these fields and we'll have to determine when/how to make use of them (ie - refactoring that controller back into the "other" / "standard" controller).

Thanks again - looking good!

**Comment by aliok** [comment]
Thanks for the feedback. All agreed!

Then I suggest we move `authSecretName` and `authSecretNamespace` from top-level to under `eventing-kafka.auth` (new field).

So, my final proposal:

```
data:
  bootstrapServers: REPLACE_WITH_CLUSTER_URL         # ------> this will be deprecated (consolidated uses this)
  authSecretName: name-of-your-secret-for-kafka-auth         # -------> will be deprecated
  authSecretNamespace: namespace-of-your-secret-for-kafka-auth                   # -------> will be deprecated
  sarama: |
    Version: 2.0.0 # Kafka Version Compatibility From Sarama's Supported List (Major.Minor.Patch)
    ...
  eventing-kafka: |
    channel:
      receiver:             # -----------> only to be used in distributed ch's dispatcher
        cpuRequest: 100m
        memoryRequest: 50Mi
        replicas: 1
      dispatcher:           # -----------> to be used in both ch's dispatchers
        cpuRequest: 100m
        memoryRequest: 50Mi
        replicas: 1
      auth:
        secretName: name-of-your-secret-for-kafka-auth         # -------> will be moved here
        secretNamespace: namespace-of-your-secret-for-kafka-auth                   # -------> will be moved here
      kafka:
        brokers: REPLACE_WITH_CLUSTER_URL      # ------------> consolidated will also start using this field
        topic:                # -----------> to be used in both channel impls
          defaultNumPartitions: 4
          defaultReplicationFactor: 1 # Cannot exceed the number of Kafka Brokers!
          defaultRetentionMillis: 604800000  # 1 week
        enableSaramaLogging: false
        adminType: kafka # One of "kafka", "azure", "custom"
    source:                 # reserved for future use, not going to be read right now
      foo: bar
```

I hope to start working on this in the upcoming weeks.

Just a note to myself: consolidated channel should still support the "to be deprecated" fields for a few releases.

**Comment by eric-sap** [comment]
I took some of the ideas from @aliok and @travis-minke-sap and am attempting to come up with a good combination configmap considering some of the changes from the past few months.  These are my reasonings behind the rearrangements:

- The 'enableSaramaLogging' field really doesn't fit anywhere in eventing-kafka; no matter where I put it, it was the 'sore thumb' and moving it to the sarama section seems better.  Moving the config string to 'sarama.config' should be moderately simple.
- The auth settings are more closely related to the broker and other kafka settings than they are to the channel settings
- 'authSecretName' and 'authSecretNamespace' instead of 'auth.secretName' and 'auth.secretNamespace' is a minor judgement call; no particularly strong attachment if others feel the hierarchy looks better.
- kafka as a top-level field in eventing-kafka instead of under 'channel' - If 'source' is going to be a separate field from 'channel' then it doesn't (unless I misunderstand source, which is entirely possible) make sense to bury 'kafka' inside of the 'channel' category
- cloudevents inside eventing-kafka: Technically these settings would perhaps be better suited to an 'eventing' top-level item, but I didn't think that level of purism (and taking into account that they are entirely optional) was really worth an entire overarching field.  Open to opinions here.
- distributed (and a reserved consolidated) fields under channel: This is one that I didn't find a solution that looked "great" regardless of the layout.  In the end I decided that "Having a bunch of fields that look common but are really only appropriate to one channel type" was the worse option, so I made common settings "directly under the channel field" (e.g. dispatcher is common to both) and entries for things that are specific to the distributed channel (such as the distinct receiver and the ability to have a different adminType).  This also makes it moderately simple to "pull things up" later if, for example, we decide to use the adminType configurability for the consolidated channel (requires only a tiny change to the structs and makes backwards-compatibility fairly simple).
- removing 'replicas'  This isn't strictly necessary for this issue but I am considering making this an optional field (default to 1) and encouraging administrators to use horizontalpodautoscalers to handle replicas instead of using a mandatory fixed amount here (though still allowing it to be specified for backwards-compatibility, and there being no reason not to)

```
data:
  sarama:
    enableLogging: false
    config: |
      Version: 2.0.0 # Kafka Version Compatibility From Sarama's Supported List (Major.Minor.Patch)
      ...
  eventing-kafka: |
    cloudevents:
      maxIdleConns: 1000
      maxIdleConnsPerHost: 100
    kafka:
      authSecretName: kafka-cluster
      authSecretNamespace: knative-eventing
      brokers: REPLACE_WITH_CLUSTER_URL
      topic:
        defaultNumPartitions: 4
        defaultReplicationFactor: 1 # Cannot exceed the number of Kafka Brokers!
        defaultRetentionMillis: 604800000  # 1 week
    channel:
      dispatcher:
        cpuRequest: 100m
        memoryRequest: 50Mi
      distributed:
        adminType: kafka # One of "kafka", "azure", "custom"
        receiver:
          cpuRequest: 100m
          memoryRequest: 50Mi
      consolidated:
        reserved: for-future-use
    source:
      reserved: for-future-use
```

Ali's comments about supporting the deprecated fields still apply (e.g. "if the sarama field doesn't have a config subfield, treat it as the entire sarama string," etc.).  Should we have a version number in our configmap perhaps?
