### ISSUE TITLE
[Consolidated Channel] Some of the KafkaChannel-backed Broker Triggers' Subscriptions stuck in SubscriptionNotMarkedReadyByChannel

### ISSUE THREAD

**Issue by maschmid** [knative-sandbox/eventing-kafka#536]
**Describe the bug**

After creating a bigger number of triggers (32 brokers with 8 triggers each) for KafkaChannel-backed brokers at around the same time, some of the Subscriptions are stuck in SubscriptionNotMarkedReadyByChannel 

```
oc get subscriptions  | grep Unknown
broker1-mytrigger1-8-ede8d8c2-8d3b-4bef-83e9-9d72ee974943     11m   Unknown   SubscriptionNotMarkedReadyByChannel
broker2-mytrigger2-4-714052e4-cda4-4b41-963b-5c4599c93fb2     10m   Unknown   SubscriptionNotMarkedReadyByChannel
broker20-mytrigger20-1-25ccab15-3888-42af-bbb4-a2312a4b1b42   10m   Unknown   SubscriptionNotMarkedReadyByChannel
broker21-mytrigger21-5-ea1bea16-5b55-411a-b406-92873766ab1c   10m   Unknown   SubscriptionNotMarkedReadyByChannel
broker6-mytrigger6-3-158125ee-c0e8-48c4-9bea-bc6c2ed6fbc5     10m   Unknown   SubscriptionNotMarkedReadyByChannel
broker7-mytrigger7-1-a6883e7d-4b1c-4427-a1c7-84c14423f31b     10m   Unknown   SubscriptionNotMarkedReadyByChannel
```

 **Expected behavior**
All Subscriptions should eventually become Ready 

 **To Reproduce**
https://gist.github.com/maschmid/8e174443803296d2c1f43ea90f6bad40

 **Knative release version**
consolidated kafkachannel, serving, eventing and eventing-kafka 0.20, installed via Serverless Operator on OCP 4.7 on AWS (but presumably not OpenShift-specific)

 **Additional context**

Using Strimzi -managed Kafka

```
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      auto.create.topics.enable: "false"
      log.message.format.version: "2.6"
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - authentication:
        type: tls
      name: tls
      port: 9093
      tls: true
      type: internal
    - authentication:
        type: scram-sha-512
      name: sasl
      port: 9094
      tls: true
      type: internal
    replicas: 3
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 100Gi
        type: persistent-claim
    version: 2.6.0
  zookeeper:
    replicas: 3
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
```
