### ISSUE TITLE
Unable to connect KnativeKafka to IBM Event Streams 

### ISSUE THREAD

**Issue by jeanabraham** [knative-sandbox/eventing-kafka#562]
**Describe the bug**

History: https://github.com/knative/eventing/issues/5286

Knative kafka dispatcher fails to start due to error below. But I am able to connect to the same IBM ES Bootstrap Servers from an Kafka client successfully from localhost.

`{"level":"fatal","ts":"2021-04-20T16:53:25.508Z","logger":"kafkachannel-dispatcher","caller":"dispatcher/kafkachannel.go:106","msg":"Unable to create kafka dispatcher","knative.dev/pod":"kafka-ch-dispatcher-5b457d747-xgzwr","error":"unable to create kafka producer against Kafka bootstrap servers [host1:9093 host2:9093 host3:9093] : kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","stacktrace":"knative.dev/eventing-kafka/pkg/channel/consolidated/reconciler/dispatcher.NewController\n\t/opt/app-root/src/go/src/knative.dev/eventing/pkg/cha...`

 **Expected behavior**
kafka-ch-dispatcher starts successfully

```
$oc get pods -n knative-eventing | grep kafka                                                                                                                                                          
kafka-ch-controller-69bdfc4f8d-tsf5c        1/1     Running            0          16m
kafka-ch-dispatcher-5b457d747-xgzwr         0/1     Running   7          16m
kafka-controller-manager-6d9dc87b74-npcgb   1/1     Running            0          16m
kafka-webhook-5d6b94597-pvlbk               1/1     Running            0          16m
```

 **To Reproduce**
Steps to reproduce the behavior.

1. Setup IBM Event Streams on IBM Cloud with basic configuration as the kafka provider
1. [Install Knative Kafka using Openshift Serverless](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html-single/serverless/index#serverless-install-kafka-odc_serverless-kafka)

Error encountered post successful install, but during deployment of pod.

 **Release version**
Red Hat OpenShift Serverless 1.13.0 uses Knative Eventing 0.19.2.

**Comment by matzew** [comment]
looking at the other ticket (not sure why we need two).


So, for SASL with TLS, can you try this:

1. create a secret like:

```
kubectl create secret --namespace my-namespace generic my-sasl-secret \\
    --from-literal=tls.enabled=true \
    --from-literal=password="secret" \
    --from-literal=user="JaneDoe"
```

2. have the `config-kafka` ConfigMap updated like (references: https://github.com/knative-sandbox/eventing-kafka/blob/main/test/config/config-kafka-sasl.yaml)

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-kafka
  namespace: ${SYSTEM_NAMESPACE}
data:
  # Broker URL. Replace this with the URLs for your kafka cluster,
  # which is in the format of my-cluster-kafka-bootstrap.my-kafka-namespace:9092.
  bootstrapServers: REPLACE_WITH_CLUSTER_URL
  authSecretName: my-sasl-secret
  authSecretNamespace: ${SYSTEM_NAMESPACE}
```

(the configmap is the manual install way, e.g. `k apply yaml`)

The referenced UI has some fields for that info, that the operator is setting on install:
* Bootstrap Servers
* Auth Secret Name
* Auth Secret Namespace


That said the `tls.enabled` was done in this PR: https://github.com/knative-sandbox/eventing-kafka/pull/359

Which was backported only to 0.20 and later - not the 0.19.x branches.
