### ISSUE TITLE
SASL Connection Issue with SASL_SSL + PLAIN

### ISSUE THREAD

**Issue by maarek** [knative-sandbox/eventing-kafka#623]
**Describe the bug**
I have an use case where I am interacting with a cloud provider's kafka implementation and they set up client access with mechanism `PLAIN` and  protocol `SASL_SSL`. There are no provided SSL certs or anything and it does not accept SASL_PLAINTEXT configuration.

There seems to be an issue with how sarama and or the broker is configured that does not allow sarama to connect to the broker in this configuration as it fails with `Failed to read SASL handshake header: EOF`. Maybe this is due to a self signed certificate? I am unsure.

I have found a fix that can configure sarama to connect to this configuration. Even though this is `SASL_SSL` and `PLAIN`, `TLS` needs to be enabled and `InsecureSkipVerify` needs to be enabled. No Certs need to be provided to the `TLS` configuration.

 **Expected behavior**
Sarama and by proxy Eventing-Kafka should be able to connect to the brokers by exposing the ability to configure `TLS` and `InsecureSkipVerify` even if TLS is not used. 

Maybe we can expose `InsecureSkipVerify` on either the `NET.TLS` configuration or on `NET.SASL` that would configure `TLS` enabled and `InsecureSkipVerify` if configured. 

[https://github.com/knative-sandbox/eventing-kafka/blob/2b185a9b59347cc4a16471ed0fb2ba3bdf6e1672/pkg/source/client/client.go#L72](https://github.com/knative-sandbox/eventing-kafka/blob/2b185a9b59347cc4a16471ed0fb2ba3bdf6e1672/pkg/source/client/client.go#L72)

[https://github.com/knative-sandbox/eventing-kafka/blob/ee1f70166dd0421eebc14f48367f0417c401eea1/pkg/common/client/config.go#L224](https://github.com/knative-sandbox/eventing-kafka/blob/ee1f70166dd0421eebc14f48367f0417c401eea1/pkg/common/client/config.go#L224)

**Comment by matzew** [comment]
@maarek here is what we have for the channel: 
https://github.com/knative/docs/pull/3493/files

**Comment by matzew** [comment]
For the source I used it in the past like:

```
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  bootstrapServers:
    - come-at-me-bro.some.kafka:443
  topics:
    - matzew-test-topic
  net:
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: my-sasl-secret
          key: user
      password:
        secretKeyRef:
          name: my-sasl-secret
          key: password
    tls:
      enable: true
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: ping-display

```

also, I had no SSL certs for the service
