### ISSUE TITLE
Trigger on a Broker backed by the deprecated v1alpha1 KafkaChannel repeatedly re-creates Subscription

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka#624]
**Describe the bug**

having a Broker backed by the deprecated v1alpha1 KafkaChannel:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker
data:
  channelTemplateSpec: |-
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    spec:
        numPartitions: 8
        replicationFactor: 3
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: broker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: broker
```

Creating a Trigger,
```
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger1
spec:
  broker: broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display-broker
```

repeatedly re-creates the Subscription several times per second. (Along with the updates to the Trigger and Channels, this also creates several Events per each Subscription re-created, causing a significant strain on the API server).

 **Knative release version**
0.22

**Comment by matzew** [comment]
NOTE: changing the `broker` config map to use the `v1beta1` APIs did solve this problem...

**Comment by matzew** [comment]
We do have a migration for the `KafkaChannel` here:
https://github.com/knative-sandbox/eventing-kafka/tree/release-0.22/config/post-install

But... I wonder if that will actually have any effect on the `ConfigMap` here, which uses a `channelTemplateSpec` to declare the Channel: 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker
data:
  channelTemplateSpec: |-
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    spec:
        numPartitions: 8
        replicationFactor: 3
```
