### ISSUE TITLE
defaultNumPartitions from Config-Kafka ConfigMap is not working

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/eventing-kafka#813]
**Describe the bug**

Apply the standard yaml for `consolidated-channel`, with updated `broker`, like:

```yaml
apiVersion: v1
data:
  eventing-kafka: |
    kafka:
      brokers: my-cluster-kafka-bootstrap.kafka:9092
      topic:
        defaultNumPartitions: 4
        defaultReplicationFactor: 1 # Cannot exceed the number of Kafka Brokers!
        defaultRetentionMillis: 604800000  # 1 week
  version: 1.0.0

```

seem to not recognize the `defaultNumPartitions`.  Creating a channel like:

```yaml
apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: my-testchannel
```

Does still give you a topic w/ just one partition, see:

```shell
NAME                                                                                               CLUSTER      PARTITIONS   REPLICATION FACTOR   READY
knative-messaging-kafka.default.my-testchannel                                                     my-cluster   1            1                    True

```

 **Expected behavior**
yaml works :smile_cat: 

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority
