### ISSUE TITLE
[Source] Deprecate `key-type` label and replace it with a spec field

### ISSUE THREAD

**Issue by pierDipi** [knative-sandbox/eventing-kafka#939]
**Problem**

A label for a configuration is fine if you don't have control over the CRD or for an experimental feature.

Specifying a key type is a core feature of `KafkaSource`, so I propose to introduce a new spec field as an alternative to the `key-type` label:

```yaml
spec:
  key:
    sourceType: <int | string | byte-array | float>
    targetType: <https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#type-system>
```

A spec field has many benefits over an annotation or label like validation since if I mistype the annotation key or label key I won't get any error or warning.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?
- event consumer

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?
1
