### ISSUE TITLE
Distributed channel upgrade from v0.25.5 to v0.26.3 fails during retentionDuration update

### ISSUE THREAD

**Issue by eric-sap** [knative-sandbox/eventing-kafka#952]
**Describe the bug**
After installing an empty v0.25.5 (with v0.25.2 knative-eventing) kind-cluster and creating a basic kafkachannel with minimal spec:
```
  apiVersion: messaging.knative.dev/v1beta1
  kind: KafkaChannel
  metadata:
    name: sample-kafka-channel-1
  spec:
    numPartitions: 1
    replicationFactor: 1
```
then upgrading to v0.26.3 (with v0.26.1 knative-eventing first), I see errors like this in the post-install job log
```
"error": "admission webhook \"validation.webhook.kafka.messaging.knative.dev\" denied the request: validation failed: Immutable fields changed (-old +new): spec\n{v1beta1.KafkaChannelSpec}.RetentionDuration:\n\t-: \"\"\n\t+: \"PT168H\"\n"
```

 **Expected behavior**
Kafkachannels created in v0.25.x should upgrade to v0.26.x without issues when the channel-post-install.yaml is applied.

 **To Reproduce**
- Install v0.25.5
- Create basic kafkachannel
- Install v0.26.3
- Apply the post-install from https://github.com/knative-sandbox/eventing-kafka/releases/download/v0.26.3/channel-post-install.yaml
- Note that the post-install pod is in a crash loop

 **Knative release version**
v0.25.2 to v0.26.1 (upgrade)

 **Additional context**
I haven't yet noted exactly which sub-versions may or may not cause these issues; I was just using v0.25.5 and v0.26.3 as there were the latest as of this writing.
